library(rio)
library(Amelia)
library(tidyverse)
library(gridExtra)
library(caret)
library(rpart)
library(gbm)
library(randomForest)
library(devtools)
library(woe)
library(ResourceSelection)
library(ROCR)
store_demo <- read.csv(file = 'data/storedemographicdata.csv',header = T,sep = "," )
store_sales <- read.csv(file = 'data/storesalesdata.csv')
store_loc <- read.csv(file = 'data/storeinformation.csv',header = T,sep = ",")

